### ISSUE TITLE
zadachi-simeon prisadov

### ISSUE THREAD

**Issue by madoxxs** [HackBulgaria/Programming101-3#4]
https://gist.github.com/madoxxs

**Comment by syndbg** [comment]
Здравей, madoxxs.

Благодаря за изявеното желание за участие в Programming 101-3. Ще се опитам да те напътствам с кандидатстването. То минава през няколко стъпки:
1. Трябва да кандидатстваш през https://hackbulgaria.com/apply/ за `Programming 101-3`. 
2. На имейла ти ще получиш твоята парола за системата, с която ще се впишеш.
3. След това в профила ти на https://hackbulgaria.com/accounts/profile/ ще видиш URL за предаване на задачи за `Programming 101-3`.
4. На гореспоменатият URL предаваш задачите, които си пуснал в Github като Issues.

Успех! :smile: 

П.С Това се отнася и за #1, #2, #3

**Comment by RadoRado** [comment]
inb4 "Как да си предам задачите?" guide :laughing:
